-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:BOE 0x0A81",
  mode = "1920x1080@120.00",
  position = "0x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "6", monitor = "desc:BOE 0x0A81", default = true, persistent = true })
hl.workspace_rule({ workspace = "7", monitor = "desc:BOE 0x0A81" })
hl.workspace_rule({ workspace = "8", monitor = "desc:BOE 0x0A81" })
hl.workspace_rule({ workspace = "9", monitor = "desc:BOE 0x0A81" })
hl.workspace_rule({ workspace = "10", monitor = "desc:BOE 0x0A81" })
