#!#!# Whisker keybinds for Hyprland #!#!#

## General Keybinds ##
# Lock screen
bind = SUPER, L, exec, quickshell -p ~/.config/quickshell/whisker ipc call lockscreen lock
bind = SUPER, L, exec, quickshell -p ~/.config/quickshell/whisker ipc call lockscreen lock

# Region screenshot
bind = SUPER+Shift, S, exec, quickshell -p ~/.config/quickshell/whisker ipc call screen capture
bind = SUPER+Shift, S, exec, quickshell -p ~/.config/quickshell/whisker ipc call screen capture




## Applications ##
# App Launcher
# bindr = SUPER, SUPER_L, exec, whisker ipc launcher toggle

# Whisker Settings
# bind = Super, I, exec, whisker ipc settings open '""'
bind = Super, I, exec, quickshell -p ~/.config/quickshell/whisker ipc call settings open '""'

# Clipboard History
# bind = Super, V, exec, whisker ipc clipboard toggle
bind = Super, V, exec, quickshell -p ~/.config/quickshell/whisker ipc call clipboard toggle
